# **Handling Imbalanced Dataset With Machine Learning**

In [26]:
!pip install imbalanced-learn

In [27]:
import pandas as pd
df=pd.read_csv('creditcard002.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0


In [28]:
df.shape

(284807, 31)

In [29]:
df.isnull().sum()

,0
Time,0
V1,0
V2,0
V3,0
V4,0
V5,0
V6,0
V7,0
V8,0
V9,0


In [30]:
df.isnull().count()

,0
Time,284807
V1,284807
V2,284807
V3,284807
V4,284807
V5,284807
V6,284807
V7,284807
V8,284807
V9,284807


In [31]:
# Dependent Feature
df['Class'].value_counts()

,count
Class,
0,284315
1,492


In [32]:
### Independent and Dependent Features
x=df.drop('Class',axis=1)
y=df['Class']

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)

**Cross Validation Like KFOLD and Hyperparameter Tuning**

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
import numpy as np

In [35]:
10.0** np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [36]:
log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [37]:
# import pandas as pd

# Combine x_train and y_train to ensure row-wise NaN handling
# train_df = pd.concat([x_train, y_train], axis=1)

# Drop rows with any NaN values
# train_df_cleaned = train_df.dropna()

# Split back into x_train and y_train
# x_train_cleaned = train_df_cleaned.drop('Class', axis=1)
# y_train_cleaned = train_df_cleaned['Class']

# Now fit GridSearchCV with the cleaned data
clf = GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l2']},
             scoring='f1_macro')

In [38]:
y_pred=clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85274    33]
 [   46    90]]
0.9990754069964772
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.73      0.66      0.69       136

    accuracy                           1.00     85443
   macro avg       0.87      0.83      0.85     85443
weighted avg       1.00      1.00      1.00     85443



In [39]:
x_train.shape

(199364, 30)

In [40]:
y_train.value_counts()

,count
Class,
0,199008
1,356


In [41]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)


RandomForestClassifier()

In [42]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85302     5]
 [   27   109]]
0.9996254813150287
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.96      0.80      0.87       136

    accuracy                           1.00     85443
   macro avg       0.98      0.90      0.94     85443
weighted avg       1.00      1.00      1.00     85443



##**Class_weight**
**Use this techinique (Class_weight) when your dataset is to much long(lot of imbalanced values)**

In [43]:
# Use when you have lot of imbalanced data
class_weight=dict({0:1,1:100})


In [44]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(x_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [45]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85303     4]
 [   29   107]]
0.9996137776061234
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.96      0.79      0.87       136

    accuracy                           1.00     85443
   macro avg       0.98      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



## **Under Sampling**

**Never do Under Sampling unless or untill your dataset is vary-vary less**

In [53]:
y_train.value_counts()

,count
Class,
0,199008
1,356


In [54]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(sampling_strategy=0.8)
x_train_ns,y_train_ns=ns.fit_resample(x_train,y_train)
print('The number of classes before fit: {}'.format(Counter(y_train)))
print('The number of classes after fit: {}'.format(Counter(y_train_ns)))

The number of classes before fit: Counter({0: 199008, 1: 356})
The number of classes after fit: Counter({0: 445, 1: 356})


In [55]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(x_train_ns,y_train_ns)


RandomForestClassifier()

In [56]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[60376 24931]
 [    7   129]]
0.7081329073183292
              precision    recall  f1-score   support

           0       1.00      0.71      0.83     85307
           1       0.01      0.95      0.01       136

    accuracy                           0.71     85443
   macro avg       0.50      0.83      0.42     85443
weighted avg       1.00      0.71      0.83     85443



##**Over Sampling**

In [57]:
from imblearn.over_sampling import RandomOverSampler

In [62]:
os=RandomOverSampler(sampling_strategy=0.75)
x_train_os,y_train_os=os.fit_resample(x_train,y_train)
print("The number of classes before fit{}".format(Counter(y_train)))
print('The number of classes after fit{} '.format(Counter(y_train_os)))

The number of classes before fitCounter({0: 199008, 1: 356})
The number of classes after fitCounter({0: 199008, 1: 149256}) 


In [63]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(x_train_os,y_train_os)


RandomForestClassifier()

In [61]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85302     5]
 [   25   111]]
0.9996488887328394
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.96      0.82      0.88       136

    accuracy                           1.00     85443
   macro avg       0.98      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



**Important Interview Question:-> How to Handle Imblanced data-set**

"If I get an imbalanced dataset, I would first understand the class distribution and the business problem. I wouldn't rely only on accuracy; I would evaluate precision, recall, F1-score, ROC-AUC and, where appropriate, PR-AUC.

Then, based on the dataset size and imbalance ratio, I could try techniques such as under-sampling, over-sampling or SMOTE. I would be careful with under-sampling because it removes observations.

I would also use class-weighted models such as Random Forest or XGBoost. Based on domain knowledge, I would determine whether false positives or false negatives are more costly. Then I could tune the classification threshold—for example, from 0.5 to 0.6 or 0.7—to achieve the desired precision-recall trade-off. Finally, I would compare these approaches using cross-validation and select the approach that gives the best business-relevant performance."

##**SMOTETomek**

Create new points nearest to the vlues

In [ ]:
from imblearn.combine import SMOTETomek

In [ ]:
os=SMOTETomek(0.75)
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

##**Ensemble Techniques**

In [ ]:
from imblearn.ensemble import EasyEnsembleClassifier

In [ ]:
easy=EasyEnsembleClassifier()
easy.fit(X_train,y_train)

In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))